//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokYonetimi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faturalar> Faturalar { get; set; }
        public virtual DbSet<Kisiler> Kisiler { get; set; }
        public virtual DbSet<Kisiler_Musteriler> Kisiler_Musteriler { get; set; }
        public virtual DbSet<Kisiler_Personeller> Kisiler_Personeller { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Stoklar> Stoklar { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}
