//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokYonetimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int kisiId { get; set; }
        public string isim { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string mailAdresi { get; set; }
        public string sifre { get; set; }
        public string resim { get; set; }
    
        public virtual Kisiler_Musteriler Kisiler_Musteriler { get; set; }
        public virtual Kisiler_Personeller Kisiler_Personeller { get; set; }
    }
}
