//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokYonetimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler_Personeller
    {
        public int personelId { get; set; }
        public string sicilNo { get; set; }
        public int kisiId { get; set; }
    
        public virtual Kisiler Kisiler { get; set; }
    }
}
