//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokYonetimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int siparisId { get; set; }
        public string siparisAdedi { get; set; }
        public string siparisTarihi { get; set; }
        public string fiyat { get; set; }
        public int musteriId { get; set; }
        public int urunId { get; set; }
        public int faturaId { get; set; }
    
        public virtual Faturalar Faturalar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
