//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokYonetimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoklar
    {
        public int stokId { get; set; }
        public int urunId { get; set; }
        public string olusturmaTarihi { get; set; }
        public string adet { get; set; }
        public string adetFiyat { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
